services:
  harmony_web:
    build: .
    container_name: harmony_web
    expose:
      - "5000"  # internal port
    networks:
      - harmonyweb

  harmony_nginx:
    image: nginx:alpine
    container_name: harmony_nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - harmony_web
    networks:
      - harmonyweb

networks:
  harmonyweb:
    driver: bridge